### ISSUE TITLE
Does not work in some APP

### ISSUE THREAD

**Issue by Skyxim** [thealpa/SaneSideButtons#15]
device: Mac mini
os: macOS 13

What I find now are system settings, app stores and vscode.

**Comment by thealpa** [comment]
The way SaneSideButtons works is by simulating a three finger swipe whenever the side buttons on your mouse are pressed. Apps to be supported by SaneSideButtons therefore need to support trackpad gestures. Some apps like VSCode support mouse buttons for navigation out of the box. You can try to disable SaneSideButtons for these kind of applications. Otherwise there is no way to fix this unfortunately.

**Comment by t-fritsch** [comment]
for anyone looking for this, the way to disable SaneSideButtons in vscode is here : https://github.com/thealpa/SaneSideButtons/issues/7#issuecomment-3210191885
> Open the SaneSideButtons menu bar while the app you want to ignore is in the foreground. Check "Ignore YourApplication".

works like a charm !! (edit : thanks a lot to @thealpa for the great work !)
