### ISSUE TITLE
Doesn't seem to be working in Zotero

### ISSUE THREAD

**Issue by chelseas** [thealpa/SaneSideButtons#17]
title says it all. Trying to use within-document links to navigate to different sections and back to the table of contents page.

**Comment by thealpa** [comment]
The way SaneSideButtons works is by simulating a three finger swipe. Apps to be supported by SaneSideButtons therefore need to support trackpad gestures. Some apps support mouse buttons for navigation out of the box. You can try to disable SaneSideButtons for these kind of applications. Otherwise there is no way to fix this unfortunately. You would need to ask the developers of Zotero to be a good macOS citizen and implement support for swipe gestures.
